---
title: "Logging Rmd"
author: "Andrea Melloncelli"
date: "2/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include=FALSE}
library(aktools)
flog.threshold("debug")
flog.appender(appender.file("./example-logging-rmd.log"))
flog.info("Begin Rmd render ----------------------------")

flog.info("Reading inputs")
ds <- mtcars
```

## Manipulation

This function will take 5 seconds. And the time passed is in *example-logging-rmd.log*:

```{r, include=FALSE}
manipulation_function <- function(ds) {
  Sys.sleep(5)
  ds[,c('cyl','mpg')]
}

flog.info("Manipulating..")
masterShinyRmd:::log_time("manipulation", {
  ds_reduced <- manipulation_function(ds)
})
```

```{r}
ds_reduced
```

## R Markdown

```{r, include=FALSE}
flog.info("Reading inputs")
```


```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
flog.info("Plotting")
plot(pressure)
```

```{r, include=FALSE}
flog.info("End Rmd render ------------------------------")
```

